# Generated by Django 2.2.1 on 2019-05-13 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.FloatField(blank=True, default=2.0, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_date_year', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('d_major', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_sem', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('totalcredit', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('givencredit', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('fcredits', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can access the admin site.', verbose_name='Staff Status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Super User Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllOpenCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10, null=True)),
                ('long_name', models.CharField(max_length=150)),
                ('credit', models.CharField(max_length=10, null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('schedule', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenCoursesForYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10, null=True)),
                ('long_name', models.CharField(max_length=150)),
                ('credit', models.CharField(max_length=10, null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('schedule', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=20)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100, null=True)),
                ('credit', models.PositiveSmallIntegerField(null=True)),
                ('grade', models.CharField(max_length=5, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
