# Generated by Django 2.2.1 on 2019-05-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='department',
            new_name='coursecode',
        ),
    ]
