# Generated by Django 2.2.1 on 2019-05-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190515_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user account should be considered active. Set this flag to False instead of deleting accounts.', verbose_name='Active Status'),
        ),
    ]
