# Generated by Django 2.2.1 on 2019-05-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopencourses',
            name='prereq',
            field=models.CharField(default='girilmemis', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opencoursesforyou',
            name='prereq',
            field=models.CharField(default='girilmemis', max_length=10, null=True),
        ),
    ]
