# Generated by Django 2.2.1 on 2019-05-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20190515_0533'),
        ('schedule', '0002_auto_20190520_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='opencourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.OpenCoursesForYou'),
        ),
    ]
